name: PR auto-generator

on:
  workflow_dispatch:
    inputs:
      FROM_BRANCH:
        description: Base branch
        type: string
      TO_BRANCH:
        description: Destination branch
        type: string
  push:
    branches-ignore: main

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Derive from branch name
        run: |
            # do custom parsing of your code / date to derive a branch from
            # PR_BRANCH_FROM = '$inputs.from_branch'
            echo "PULL_REQUEST_FROM_BRANCH=${inputs.FROM_BRANCH}" >> $GITHUB_ENV
      
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: ${{ inputs.TO_BRANCH }}
