
name: Build and push to docker

on:
  workflow_dispatch:
    inputs:
      tag_input:
        description: Version input
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: First test job
        run: echo "The job's step is '$GITHUB_JOB'"
  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push  
        uses: docker/build-push-action@v4
        env:
          IMAGE_NAME: jpmorelli/awesomecicd
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}":"${GITHUB_SHA}
