name: Build and push to docker

on:
  workflow_dispatch:
    
env:
  IMAGE_NAME: jpmorelli/awesomecicd
  IMAGE_TAG: $GITHUB_SHA

jobs:
  docker:
          runs-on: ubuntu-latest
          steps:
            -
              name: First test job
              run: echo "The job's step is '$GITHUB_JOB'"
        
            -
              name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
              name: Build and push
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: $IMAGE_NAME:$IMAGE_TAG
