name: Build and push to docker

on:
  workflow_dispatch:
    
env:
  IMAGE_NAME: jpmorelli/awesomecicd
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

jobs:
  run-tests:
    - name: First test job
    - run: echo "The job's stage is '$CI_JOB_STAGE'"

  build-image:
    - name: Build image
    - image: docker:20.10.16
    - services:
      - docker:20.10.16-dind
    - variables:
      DOCKER_TLS_CERTDIR: "/certs"
    - stage: build
    - before_script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
    run:
      echo "The job's stage is '$CI_JOB_STAGE'"
      docker build -t $IMAGE_NAME:$IMAGE_TAG .
      docker push $IMAGE_NAME:$IMAGE_TAG
