name: Just to say hello

on:
  workflow_dispatch:
    inputs:
      who-to-greet:  # id of input
            description: 'Person to act with. Valid options: JP|Another stupid'
            required: true
            default: 'JP'
            type: choice
            options:
            - JP
            - Another stupid

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: jpmorelli/hello-world-composite-action@v1
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
